---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: rockylinux:8.7
    command: /lib/systemd/systemd
    privileged: true
    pre_build_image: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    published_ports:
      - 0.0.0.0:8080:80
provisioner:
  name: ansible
verifier:
  name: ansible
